In [3]:
import os

# Change directory Pandas
os.chdir('/Users/martaspizzichino/Desktop/Pandas')

# Verify that the Directory was properly changed
print(os.getcwd())  # Questo dovrebbe restituire /Users/martaspizzichino/Desktop/Pandas

# File loans.csv
import pandas as pd
df = pd.read_csv('loans.csv')

# Visualizza le prime 5 righe del DataFrame
print(df.head())

/Users/martaspizzichino/Desktop/Pandas
   loan_id       loan_name original_language  \
0   657307            Aivy           English
1   657259  Idalia Marizza           Spanish
2   658010           Aasia           English
3   659347         Gulmira           Russian
4   656933         Ricky\t           English

                                         description  \
0  Aivy, 21 years of age, is single and lives in ...
1  Doña Idalia, esta casada, tiene 57 años de eda...
2  Aasia is a 45-year-old married lady and she ha...
3  Гулмире 36 лет, замужем, вместе с супругом вос...
4  Ricky is a farmer who currently cultivates his...

                              description_translated  funded_amount  \
0                                                NaN          125.0
1  Idalia, 57, is married and lives with her husb...          400.0
2                                                NaN          400.0
3  Gulmira is 36 years old and married.  She and ...          625.0
4                                                NaN          425.0

   loan_amount  status  activity_name  sector_name  ...  \
0        125.0  funded  General Store       Retail  ...
1        400.0  funded  Used Clothing     Clothing  ...
2        400.0  funded  General Store       Retail  ...
3        625.0  funded        Farming  Agriculture  ...
4        425.0  funded        Farming  Agriculture  ...

                     raised_time lender_term num_lenders_total  \
0  2014-01-15 04:48:22.000 +0000         7.0                 3
1  2014-02-25 06:42:06.000 +0000         8.0                11
2  2014-01-24 23:06:18.000 +0000        14.0                16
3  2014-01-22 05:29:28.000 +0000        14.0                21
4  2014-01-14 17:29:27.000 +0000         7.0                15

  num_journal_entries num_bulk_entries  \
0                   2                1
1                   2                1
2                   2                1
3                   2                1
4                   2                1

                                                tags borrower_genders  \
0                                                NaN           female
1                                                NaN           female
2  #Woman Owned Biz, #Supporting Family, user_fav...           female
3                                      user_favorite           female
4           #Animals, #Eco-friendly, #Sustainable Ag             male

   borrower_pictured repayment_interval distribution_model
0               true          irregular      field_partner
1               true            monthly      field_partner
2               true            monthly      field_partner
3               true            monthly      field_partner
4               true             bullet      field_partner

[5 rows x 31 columns]

In [19]:
# List of languages of interest
languages = ['English', 'Spanish']

# Filter the dataframe to include only rows where:
# - 'original_language' is in the list of 'languages'
# - 'funded_amount' is greater than 1000
df_filtered = df[(df['original_language'].isin(languages)) & (df['funded_amount'] > 1000)]

# Display the first 5 rows of the filtered dataframe
print(df_filtered.head())

    loan_id    loan_name original_language  \
7    661601    Francisco           Spanish
12   660363     Bayarmaa           English
16   664664  Fidel Ángel           Spanish
24   958688      Ketevan           English
27   959968       Stepan           English

                                          description  \
7   Francisco, es jefe de su hogar, vive con su fa...
12  Bayarmaa is 39 years old and lives with her hu...
16  Fidel de 56 años de edad  estudio segundo grad...
24  Tamar is 45 years old. She is married and live...
27  Stepan is musician by profession, working in l...

                               description_translated  funded_amount  \
7   Francisco is the head of his household, living...         1600.0
12                                                NaN         1175.0
16  Fidel is 56 years old and studied as far as se...         1500.0
24  Tamar is 45 years old. She is married and live...         1300.0
27  Stepan is musician by profession, working in l...         1125.0

    loan_amount  status        activity_name  sector_name  ...  \
7        1600.0  funded          Agriculture  Agriculture  ...
12       1175.0  funded        Grocery Store         Food  ...
16       1500.0  funded          Agriculture  Agriculture  ...
24       1300.0  funded  Fruits & Vegetables         Food  ...
27       1125.0  funded  Musical Instruments         Arts  ...

                      raised_time lender_term num_lenders_total  \
7   2014-02-22 17:52:56.000 +0000        26.0                49
12  2014-01-22 20:01:16.000 +0000        26.0                24
16  2014-02-26 21:25:29.000 +0000        15.0                53
24  2015-10-23 04:13:54.000 +0000        20.0                44
27  2015-10-14 16:53:37.000 +0000        26.0                25

   num_journal_entries num_bulk_entries  \
7                    1                1
12                   1                1
16                   2                1
24                   1                1
27                   2                1

                                                 tags borrower_genders  \
7   user_favorite, #Biz Durable Asset, #Animals, #...             male
12                                                NaN           female
16                                                NaN             male
24  user_favorite, user_favorite, #Health and Sani...           female
27                             #Parent, user_favorite             male

    borrower_pictured repayment_interval distribution_model
7                true          irregular      field_partner
12               true            monthly      field_partner
16               true             bullet      field_partner
24               true            monthly      field_partner
27               true            monthly      field_partner

[5 rows x 31 columns]

In [20]:
# Sort the dataframe by 'funded_amount' in descending order
# and by 'original_language' in ascending order
df_sorted = df.sort_values(by=['funded_amount', 'original_language'], ascending=[False, True])

# Display the first 5 rows of the sorted dataframe
print(df_sorted.head())

         loan_id              loan_name original_language  \
56589     722883         Kreyol Essence           English
238573   1433600         Cacao de Aroma           English
397051   1398161              Dlo Haiti           English
1252741  1396525         Mavuno Harvest           English
871743   1359159  Global Trauma Project           English

                                               description  \
56589    Kreyòl Essence is a social business creating ...
238573   This is Cacao de Aroma’s second loan on Kiva. ...
397051   This DloHaiti’s second loan on Kiva after succ...
1252741  Charity: "Give a woman a fruit, feed her for a...
871743   Problem\n<p>Conflict-affected regions exhibit ...

                                    description_translated  funded_amount  \
56589    Kreyòl Essence is a social business creating ...       100000.0
238573   This is Cacao de Aroma’s second loan on Kiva. ...       100000.0
397051   This DloHaiti’s second loan on Kiva after succ...       100000.0
1252741  Charity: "Give a woman a fruit, feed her for a...       100000.0
871743   Problem\n<p>Conflict-affected regions exhibit ...        80000.0

         loan_amount  status       activity_name  sector_name  ...  \
56589       100000.0  funded         Agriculture  Agriculture  ...
238573      100000.0  funded         Agriculture  Agriculture  ...
397051      100000.0  funded  Goods Distribution    Wholesale  ...
1252741     100000.0  funded             Farming  Agriculture  ...
871743       80000.0  funded              Health       Health  ...

                           raised_time lender_term num_lenders_total  \
56589    2014-06-19 20:21:04.000 +0000        75.0              2986
238573   2017-12-29 02:26:15.000 +0000         8.0              2964
397051   2017-11-07 04:04:13.000 +0000        20.0              2950
1252741  2017-10-28 19:30:02.000 +0000        14.0              3045
871743   2017-08-21 09:46:52.000 +0000        10.0              2665

        num_journal_entries num_bulk_entries  \
56589                    10                5
238573                    1                1
397051                    2                1
1252741                   2                1
871743                    1                1

                                                      tags borrower_genders  \
56589    user_favorite, user_favorite, user_favorite, u...           female
238573   user_favorite, #Repeat Borrower, #Vegan, #Sust...             male
397051   user_favorite, user_favorite, #Repeat Borrower...             male
1252741  user_favorite, user_favorite, user_favorite, u...           female
871743   #Health and Sanitation, user_favorite, user_fa...           female

         borrower_pictured repayment_interval distribution_model
56589                 true          irregular      field_partner
238573                true             bullet      field_partner
397051                true          irregular      field_partner
1252741               true            monthly      field_partner
871743                true          irregular      field_partner

[5 rows x 31 columns]

In [21]:
# Group by 'sector_name' and calculate the sum of 'funded_amount' for each sector
df_grouped = df.groupby('sector_name')['funded_amount'].sum().reset_index()

# Display the grouped data
print(df_grouped)

       sector_name  funded_amount
0      Agriculture    263018585.0
1             Arts     25730180.0
2         Clothing     80023415.0
3     Construction     17463740.0
4        Education     44216020.0
5    Entertainment      2421945.0
6             Food    256704305.0
7           Health     16515725.0
8          Housing     41154350.0
9    Manufacturing     13627775.0
10    Personal Use     22328075.0
11          Retail    218881545.0
12        Services     98160460.0
13  Transportation     27225700.0
14       Wholesale      2713350.0

In [11]:
df = pd.read_csv('/Users/martaspizzichino/Desktop/Pandas/loans.csv')

In [12]:
# Create a new column 'loan_category' based on 'funded_amount' using apply() and lambda
df['loan_category'] = df['funded_amount'].apply(lambda x: 'High' if x > 1000 else 'Low')

# Display the first 5 rows of the dataframe with the new column
print(df.head())

   loan_id       loan_name original_language  \
0   657307            Aivy           English
1   657259  Idalia Marizza           Spanish
2   658010           Aasia           English
3   659347         Gulmira           Russian
4   656933         Ricky\t           English

                                         description  \
0  Aivy, 21 years of age, is single and lives in ...
1  Doña Idalia, esta casada, tiene 57 años de eda...
2  Aasia is a 45-year-old married lady and she ha...
3  Гулмире 36 лет, замужем, вместе с супругом вос...
4  Ricky is a farmer who currently cultivates his...

                              description_translated  funded_amount  \
0                                                NaN          125.0
1  Idalia, 57, is married and lives with her husb...          400.0
2                                                NaN          400.0
3  Gulmira is 36 years old and married.  She and ...          625.0
4                                                NaN          425.0

   loan_amount  status  activity_name  sector_name  ... lender_term  \
0        125.0  funded  General Store       Retail  ...         7.0
1        400.0  funded  Used Clothing     Clothing  ...         8.0
2        400.0  funded  General Store       Retail  ...        14.0
3        625.0  funded        Farming  Agriculture  ...        14.0
4        425.0  funded        Farming  Agriculture  ...         7.0

  num_lenders_total num_journal_entries num_bulk_entries  \
0                 3                   2                1
1                11                   2                1
2                16                   2                1
3                21                   2                1
4                15                   2                1

                                                tags  borrower_genders  \
0                                                NaN            female
1                                                NaN            female
2  #Woman Owned Biz, #Supporting Family, user_fav...            female
3                                      user_favorite            female
4           #Animals, #Eco-friendly, #Sustainable Ag              male

  borrower_pictured  repayment_interval distribution_model loan_category
0              true           irregular      field_partner           Low
1              true             monthly      field_partner           Low
2              true             monthly      field_partner           Low
3              true             monthly      field_partner           Low
4              true              bullet      field_partner           Low

[5 rows x 32 columns]